### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by kevin4dhd** [aruppi/animeflv#11]
Error: Request failed with status code 403
![image](https://user-images.githubusercontent.com/22886367/129939419-643659cd-f8f8-4d37-b703-147b65462ae9.png)

**Comment by Darkangeel-hd** [comment]
this project is not currently receiving any kind of support due to staff having no time.
the error may be due to some call to an external site
without the complete stack trace i cannot tell you in which file the error is in.

Nevertheless, i suggest u look for another animeflv scrapper project, as this one is not maintained anymore and there is no telling if it will be.
